###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Badhus",
  "description": "Bada",
  "symbol": "Delfin"
}

###
GET http://localhost:8080/api/locations/public

###
GET http://localhost:8080/api/categories
###
POST http://localhost:8080/api/location
Content-Type: application/json
//Testing gpd key
//Testar igen
//Testar igen
{
  "name": "Kaktusparken",
  "category_id": 1,
  "description": "pass upp för kaktus",
  "coordinate": {
    "type": "Point",
    "coordinates": [15.634, 58.411]
  }




}

###
DELETE  http://localhost:8080/api/location/delete/19

###
PUT http://localhost:8080/api/location/update/1
Content-Type: application/json

{
"name": "Eneby",
  "category_id": 1,
  "description": "Fin park i Eneby",
  "coordinate": {
    "type": "Point",
    "coordinates": [58.411,15.634]
    }
}

###
GET http://localhost:8080/api/locations/public/area?radius=5000&lat=58.5935&lon=16.1869
