###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Badhus",
  "description": "Bada",
  "symbol": "Delfin"
}

###
GET http://localhost:8080/api/locations/public

###
GET http://localhost:8080/api/categories